
language: python
python: 2.7
branches:
  except:
    - gh-pages
env:
  - TOX_ENV=py27
before_install:
  - sudo apt-get -qq update
install:
  - python -m pip install -U pip setuptools
  - pip install -U six
  - pip install codecov
  - pip install tox
script:
  - tox
after_success:
  - codecov
